server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:~/db;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: guan
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    initialization-mode: always

#  datasource:
#    name: estate
#    url: jdbc:mysql://localhost:3306/estate?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # 自动创建表以及更新表结构，生产环境慎用
    show-sql: true # 打印执行的SQL
  h2:
    console:
      path: /h2-console
      enabled: true